---
# Use Travis' Ubuntu Focal machines. They have more RAM.
# It does not affect which OSs we are testing, since they all provided
# by Docker containers. This simply defines which OS Docker itself will
# be running on.
os: linux
dist: focal

services:
  - docker

language: ruby

rvm:
  - 2.7.4

script:
  - docker run --privileged -d polarbearlabs/haveged:1.9.1 # https://github.com/elastic/logstash/issues/5507
  - |
    (
      if [[ -n $TRAVIS_LINT ]]; then
        make lint
      elif [[ -n $TRAVIS_UNIT ]]; then
        bundle exec rake spec
      else
        bundle exec rake beaker
      fi
    )

env:
  global:
    - LOGSTASH_VERSION=6.1.3
    - BEAKER_PE_DIR=spec/fixtures/artifacts
    - CI_SPEC_OPTIONS='--format documentation'
  matrix:
    # Do linting once.
    - TRAVIS_LINT=true

    # Run the puppet-rspec synthetic/unit tests.
    - PUPPET_VERSION=5.0.1 TRAVIS_UNIT=true
    - PUPPET_VERSION=5.1.0 TRAVIS_UNIT=true
    - PUPPET_VERSION=5.2.0 TRAVIS_UNIT=true
    - PUPPET_VERSION=5.3.3 TRAVIS_UNIT=true
    - PUPPET_VERSION=6.0.4 TRAVIS_UNIT=true
